#"ABNT" do nosso arquivo que define a formatacao e os nomes (keys)
version: '3.1'

#ex: é o cara que vai orquestrar todas as aplicacoes do projeto*
services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dataops
    ports:
      - "3306:3306"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: dataops
      POSTGRES_PASSWORD: dataops
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    #volumes:
     # - /dev/urandom:/dev/random:ro
    ports:
        - "3000:3000"
    environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: metabase
        MB_DB_PORT: 5432
        MB_DB_USER: dataops
        MB_DB_PASS: dataops
    healthcheck:
        test: curl --fail -I http://localhost:3000/api/health || exit 1
        interval: 15s
        timeout: 5s
        retries: 5

  zeppelin:
    image: apache/zeppelin:0.10.0
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
      MASTER: local[*]
    ports:
      - "8080:8080"
    volumes:
      - /private/var/services/spark/zeppelin/data:/usr/zeppelin/data
      - /private/var/services/spark/zeppelin/notebook:/usr/zeppelin/notebook
