#"ABNT" do nosso arquivo que define a formatacao e os nomes (keys)
version: '3.1'

#ex: é o cara que vai orquestrar todas as aplicacoes do projeto*
services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dataops
    ports:
      - "3306:3306"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: dataops
      POSTGRES_PASSWORD: dataops
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: dataops
      MB_DB_PASS: dataops
    ports:
      - "3000:3000"
